<?xml version="1.0" encoding="utf-8"?><Database Name="HospitalDB" Class="NurseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=laptop-a88v89ut;Initial Catalog=HospitalDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HospitalDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Nurse" Member="Nurses">
    <Type Name="Nurse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstNmae" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="payment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="timeWork" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>